### ISSUE TITLE
Icons within buttons are force to be blue

### ISSUE THREAD

**Issue by andresgalante** [auth0/cosmos#1103] opened 2018-11-20 17:42 UTC
The button component forces a special size and color when the content is an icon:

https://github.com/auth0/cosmos/blob/master/core/components/atoms/button/button.js#L158-L163

In cases like the close btn on a dialog and others, this is not desired. I suggest removing this declaration, and add a new appearance for "action" btns that looks like regular text.

Therefore we can create things like kebab menus or close btns.

Before resolving this issue please make sure the overwrite on the dialog component for the close btn is removed.

**Comment by francocorreasosa** [comment] 2018-11-20 17:44
Is this a duplicate of #841?

**Closed** 2018-11-20 17:59 UTC
Labels: 🎨styling
