### ISSUE TITLE
It would be nice to have SSR Support

### ISSUE THREAD

**Issue by davesnx** [auth0/cosmos#1430] opened 2019-01-13 17:55 UTC
**Describe the bug**
cosmos relies on window.document to be present, making SSR impossible.

**Expected behavior**
Don't do anything when there's no `document` present.

**Additional context**
I'm not pretty sure if it's in the roadmap, but it's a straight forward "feature" to have in a design system. Implementation-wise it woudn't take too much time to add a check if it exist and do anything on any case. I'm not sure if this would affect in any way the reset that you add at runtime.

As a personal example I wanted to try to create some UI with `Next` and it's not possible to use any component.

**Comment by davesnx** [comment] 2019-01-13 17:56
If there's not an issue, I'm happy to create a PR :D

**Comment by francocorreasosa** [comment] 2019-01-13 17:58
Hey @davesnx! Thanks for your report. We're always open to external contributions, so go ahead :)

=======

Duplicate of #971

**Comment by francocorreasosa** [comment] 2019-02-04 17:10
Closing as duplicate of #971

**Closed by francocorreasosa** 2019-02-04 17:10 UTC
Labels: 🙋‍♀️contributions welcome
