### ISSUE TITLE
Heading component missing H5

### ISSUE THREAD

**Issue by astanciu** [auth0/cosmos#1227] opened 2018-12-06 21:16 UTC
The `<Heading />` component does not allow size of 5. 

H5 is used in the MFA page as seen here for the **Factors** and **Policies** headings

![image](https://user-images.githubusercontent.com/1675025/49612247-1644dd80-f972-11e8-8063-0ae9d98d0509.png)

**Comment by francocorreasosa** [comment] 2018-12-06 21:54
Hey @astanciu, thank you for the report. Although I'm going to have to close this issue as is a duplicate of https://github.com/auth0/cosmos/issues/1148.

**Closed by francocorreasosa** 2018-12-06 21:55 UTC
